// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index$default(Props) {
  return React.createElement("div", {
              style: {
                fontFamily: "system-ui, sans-serif",
                lineHeight: "1.4"
              }
            }, React.createElement("h1", undefined, "안녕 나는 rescript-remix야"), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                          href: "https://remix.run/tutorials/blog",
                          rel: "noreferrer",
                          target: "_blank"
                        }, "15m Quickstart Blog Tutorial")), React.createElement("li", undefined, React.createElement("a", {
                          href: "https://remix.run/tutorials/jokes",
                          rel: "noreferrer",
                          target: "_blank"
                        }, "Deep Dive Jokes App Tutorial")), React.createElement("li", undefined, React.createElement("a", {
                          href: "https://remix.run/docs",
                          rel: "noreferrer",
                          target: "_blank"
                        }, "Remix Docs"))));
}

var $$default = Index$default;

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
